/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockUSDC__factory } from "./MockUSDC__factory";
export { RealEstateToken__factory } from "./RealEstateToken__factory";
